using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DAL.Models
{
    public enum Grade
    {
        A, B, C, D, F
    }
    public class Enrollment
    {
        //1. EnrollmentID is default primary key generated by database
        public int EnrollmentID { get; set; }
        //foreign key for Course
        public int CourseID { get; set; }
        //foreign key for Student
        public int StudentID { get; set; }
        public Grade? Grade { get; set; }

        public Course Course { get; set; }
        public Student Student { get; set; }
    }
}
